create table if not exists public.clan_rankings (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  season text not null,
  rank integer not null,
  clan text not null,
  master text,
  member_current integer not null default 0,
  member_max integer not null default 0,
  reputation bigint not null default 0,
  source text not null,
  captured_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (clan_id, season)
);

create index if not exists clan_rankings_season_rank_idx on public.clan_rankings (season, rank);
create index if not exists clan_rankings_captured_idx on public.clan_rankings (captured_at desc);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('success','error')),
  season text,
  clans_seen integer not null default 0,
  started_at timestamptz not null,
  finished_at timestamptz not null,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists sync_runs_finished_idx on public.sync_runs (finished_at desc);

alter table public.clan_rankings enable row level security;
alter table public.sync_runs enable row level security;

-- The app uses the Supabase service-role key only on the server.
-- No public INSERT/UPDATE/DELETE policies are intentionally created.
-- Add a SELECT policy only if you later expose Supabase directly to a browser.
