import ActivityTimeline from './ActivityTimeline';
import TopGainers from './TopGainers';
import AlertCenter from './AlertCenter';
import EventLog from './EventLog';
import MiniBurn from './MiniBurn';
import { PERIOD_LABELS } from '../lib/metrics';
import { downloadCsv } from '../lib/csv';

const fmt = (n) => Number(n || 0).toLocaleString();
const fmtRate = (n) => Number(n || 0).toLocaleString(undefined, { maximumFractionDigits: 0 });
const fmtSigned = (n) => n === null || n === undefined ? '—' : `${Number(n) > 0 ? '+' : ''}${fmt(n)}`;
const donationPair = (gold, token) => `${fmtSigned(gold)} / ${fmtSigned(token)}`;

export default function ClanIntelligence({ clan, rows, intel, events, alerts, periodHours, setPeriodHours, eventFilter, setEventFilter }) {
  if (!clan) return <div className="nz-empty">Select a clan to open clean clan intelligence.</div>;

  const exportCsv = () => {
    const safeClan = String(clan.clan || 'clan').replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'clan';
    downloadCsv(`nztracker-${safeClan}-${PERIOD_LABELS[periodHours] || `${periodHours}H`}.csv`, rows);
  };

  const buildDiscordPost = () => {
    const label = PERIOD_LABELS[periodHours] || `${periodHours}H`;
    const top = (intel.top || []).slice(0, 5);
    const burn = (intel.burn || []).slice(0, 10);
    const activeRows = (rows || []).filter((m) => Number(m.gain || 0) > 0).sort((a, b) => Number(b.gain || 0) - Number(a.gain || 0));
    const noGain = (rows || []).filter((m) => Number(m.gain || 0) <= 0);
    const lines = [
      `🥷 **${clan.clan || 'Clan'} — Member Intelligence**`,
      `**Rank:** #${clan.rank || '—'}  •  **REP:** ${fmt(clan.reputation)}  •  **Members:** ${clan.memberCurrent || 0}/${clan.memberMax || 0}`,
      `**Window:** ${label}`,
      '',
      `📈 **Summary**`,
      `• Total Gain: **+${fmt(intel.gain)}**`,
      `• Gain / Hour: **${fmtRate(intel.hour)}**`,
      `• Active: **${intel.active}**`,
      `• No Gain: **${intel.noGain}**`,
      `• Under 10K: **${intel.burn.length}**`,
      '',
      `🏆 **Top Gainers**`,
      ...(top.length ? top.map((m, index) => `${index + 1}. **${m.name}** — +${fmt(m.gain)} (${fmtRate(m.gainPerHour)}/hr)`) : ['• No gain recorded']),
    ];

    if (burn.length) {
      lines.push('', '🔥 **10K Burn / Below 10K**');
      lines.push(...burn.map((m) => `• **${m.name}** — ${fmt(m.current)} REP`));
    }

    lines.push('', `📋 **Member Status**`);
    lines.push(`• Showing **${activeRows.length}** members with gain and **${noGain.length}** with no gain.`);
    if (noGain.length) {
      lines.push(`• No Gain: ${noGain.slice(0, 12).map((m) => m.name).join(', ')}${noGain.length > 12 ? ` +${noGain.length - 12} more` : ''}`);
    }
    const donationRows = [...(rows || [])].filter((m) => m.donatedGold !== null && m.donatedToken !== null).sort((a, b) => Number(b.donatedGold || 0) - Number(a.donatedGold || 0));
    if (donationRows.length) {
      lines.push('', `💰 **Donations**`, '`MEMBER | GOLD | TOKEN | PREV G/T | 1H G/T | 6H G/T | 24H G/T`');
      lines.push(...donationRows.slice(0, 30).map((m) => `• **${m.name}** | ${fmt(m.donatedGold)} | ${fmt(m.donatedToken)} | ${donationPair(m.donationGainGold1H, m.donationGainToken1H)} | ${donationPair(m.donationGainGold6H, m.donationGainToken6H)} | ${donationPair(m.donationGainGold24H, m.donationGainToken24H)}`));
    }
    lines.push('', '_Generated by Ninja Zenshin Tracker_');
    return lines.join('\n');
  };

  const copyDiscordPost = async () => {
    const text = buildDiscordPost();
    try {
      await navigator.clipboard.writeText(text);
      window.dispatchEvent(new CustomEvent('nztracker-toast', { detail: 'Discord post copied to clipboard' }));
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.setAttribute('readonly', '');
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      textarea.remove();
      window.dispatchEvent(new CustomEvent('nztracker-toast', { detail: 'Discord post copied to clipboard' }));
    }
  };

  return (
    <div className="nz-intel">
      <div className="nz-intel-title">
        <div>
          <span className="nz-kicker">CLAN INTELLIGENCE</span>
          <h2>#{clan.rank} {clan.clan}</h2>
          <p>{clan.master || '—'} · {clan.memberCurrent || 0}/{clan.memberMax || 0} members · {fmt(clan.reputation)} REP</p>
        </div>
        <div className="nz-intel-actions">
          <div className="periods">
            {Object.entries(PERIOD_LABELS).map(([hours, label]) => (
              <button key={hours} className={`nz-btn ${Number(hours) === periodHours ? 'active' : ''}`} onClick={() => setPeriodHours(Number(hours))}>{label}</button>
            ))}
          </div>
          <button className="nz-btn" onClick={copyDiscordPost}>COPY DISCORD POST</button>
          <button className="nz-btn" onClick={exportCsv}>EXPORT CSV</button>
        </div>
      </div>
      <div className="nz-metrics">
        <div><span>TOTAL GAIN</span><b>+{fmt(intel.gain)}</b></div>
        <div><span>GAIN / HR</span><b>{fmtRate(intel.hour)}</b></div>
        <div><span>ACTIVE</span><b>{intel.active}</b></div>
        <div><span>NO GAIN</span><b>{intel.noGain}</b></div>
        <div><span>10K BURN</span><b>{intel.burn.length}</b></div>
      </div>
      <div className="nz-intel-grid">
        <TopGainers members={intel.top} />
        <MiniBurn members={intel.burn} />
        <ActivityTimeline events={events} />
        <AlertCenter alerts={alerts} />
        <EventLog events={events} filter={eventFilter} setFilter={setEventFilter} />
      </div>
      <div className="nz-member-table">
        <div className="nz-panel-head">
          <div>
            <h3>Member intelligence</h3>
            <span className="nz-table-subtitle">REP activity for the selected {PERIOD_LABELS[periodHours] || `${periodHours}H`} window</span>
          </div>
          <span className="nz-muted">{rows.length} members</span>
        </div>
        <div className="nz-table-wrap nz-member-intel-wrap">
          <table className="nz-member-intel-table">
            <thead><tr><th>MEMBER</th><th>REP</th><th>GAIN</th><th>GAIN / HR</th><th>STATUS</th><th>GOLD</th><th>TOKEN</th><th>PREV G/T</th><th>1H G/T</th><th>6H G/T</th><th>24H G/T</th></tr></thead>
            <tbody>
              {rows.length ? rows.map((m) => (
                <tr key={m.id}>
                  <td className="member-name" title={m.name}>{m.name}</td>
                  <td>{fmt(m.current)}</td>
                  <td className={`gain ${m.gain > 0 ? 'has-gain' : 'zero-gain'}`}>{m.gain > 0 ? `+${fmt(m.gain)}` : '0'}</td>
                  <td className="rate">{m.gain > 0 ? `${fmtRate(m.gainPerHour)}/hr` : '—'}</td>
                  <td><span className={`nz-status ${String(m.status).toLowerCase().replace(/\s+/g,'-')}`}>{m.status}</span></td>
                  <td>{m.donatedGold === null ? '—' : fmt(m.donatedGold)}</td>
                  <td>{m.donatedToken === null ? '—' : fmt(m.donatedToken)}</td>
                  <td>{donationPair(m.donationGainGold, m.donationGainToken)}</td>
                  <td>{donationPair(m.donationGainGold1H, m.donationGainToken1H)}</td>
                  <td>{donationPair(m.donationGainGold6H, m.donationGainToken6H)}</td>
                  <td>{donationPair(m.donationGainGold24H, m.donationGainToken24H)}</td>
                </tr>
              )) : <tr><td colSpan="11" className="nz-empty-row">No member intelligence data available yet.</td></tr>}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
