'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';

const REFRESH_MS = 30000;
const HISTORY_KEY = 'nztracker-history-v1';
const FAVORITES_KEY = 'nztracker-favorites-v1';

const formatNumber = value => new Intl.NumberFormat('en-US').format(Number(value || 0));
const formatTime = value => value ? new Date(value).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit', second:'2-digit' }) : '—';

export default function Home() {
  const [rows,setRows]=useState([]),[season,setSeason]=useState('Season 2'),[status,setStatus]=useState('loading'),[updatedAt,setUpdatedAt]=useState(null);
  const [autoRefresh,setAutoRefresh]=useState(true),[countdown,setCountdown]=useState(30),[query,setQuery]=useState(''),[sort,setSort]=useState('rank');
  const [history,setHistory]=useState([]),[previous,setPrevious]=useState({}),[favorites,setFavorites]=useState([]),[showFavorites,setShowFavorites]=useState(false);
  const [selectedClan,setSelectedClan]=useState(null),[members,setMembers]=useState([]),[memberPrevious,setMemberPrevious]=useState({}),[memberStatus,setMemberStatus]=useState('idle'),[memberUpdatedAt,setMemberUpdatedAt]=useState(null);

  useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]'));setFavorites(JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]'));}catch{}},[]);
  const saveHistory=useCallback(snapshot=>setHistory(current=>{const next=[...current,snapshot].slice(-240);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(next));}catch{}return next;}),[]);

  const load=useCallback(async()=>{try{setStatus('loading');const res=await fetch('/api/clan-ranking',{cache:'no-store'});if(!res.ok)throw new Error();const data=await res.json();const now=new Date().toISOString();setRows(current=>{const snap={};current.forEach(r=>snap[r.clan]=r.rank);if(Object.keys(snap).length)setPrevious(snap);if(data.rows?.length)saveHistory({capturedAt:now,season:data.season,rows:data.rows});return data.rows||[];});setSeason(data.season||'Season 2');setUpdatedAt(new Date(now));setStatus('live');setCountdown(30);}catch{setStatus('error');}},[saveHistory]);

  const loadMembers=useCallback(async clan=>{if(!clan?.clanId){setMembers([]);setMemberStatus('unavailable');return;}try{setMemberStatus('loading');const res=await fetch(`/api/clan-members?clanId=${encodeURIComponent(clan.clanId)}`,{cache:'no-store'});if(!res.ok)throw new Error();const data=await res.json();setMemberPrevious(current=>{const snap={};members.forEach(m=>snap[m.name]=m.reputation);return snap;});setMembers(data.members||[]);setMemberUpdatedAt(new Date(data.fetchedAt||Date.now()));setMemberStatus('live');}catch{setMemberStatus('error');}},[members]);

  useEffect(()=>{load();},[load]);
  useEffect(()=>{if(!autoRefresh)return;const t=setInterval(load,REFRESH_MS);return()=>clearInterval(t);},[autoRefresh,load]);
  useEffect(()=>{if(!autoRefresh)return;const t=setInterval(()=>setCountdown(v=>v<=1?30:v-1),1000);return()=>clearInterval(t);},[autoRefresh]);
  useEffect(()=>{if(!autoRefresh||!selectedClan)return;const t=setInterval(()=>{const clan=rows.find(r=>r.clan===selectedClan);if(clan)loadMembers(clan);},REFRESH_MS);return()=>clearInterval(t);},[autoRefresh,selectedClan,rows,loadMembers]);

  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();let data=q?rows.filter(r=>`${r.clan} ${r.master}`.toLowerCase().includes(q)):[...rows];if(showFavorites)data=data.filter(r=>favorites.includes(r.clan));if(sort==='reputation')data.sort((a,b)=>b.reputation-a.reputation);else if(sort==='members')data.sort((a,b)=>b.memberCurrent-a.memberCurrent);else data.sort((a,b)=>a.rank-b.rank);return data;},[rows,query,sort,showFavorites,favorites]);
  const leader=rows[0],selected=selectedClan?rows.find(r=>r.clan===selectedClan):leader,totalMembers=rows.reduce((a,r)=>a+r.memberCurrent,0),totalSlots=rows.reduce((a,r)=>a+r.memberMax,0),averageRep=rows.length?Math.round(rows.reduce((a,r)=>a+r.reputation,0)/rows.length):0;
  const selectedHistory=history.filter(h=>h.rows?.some(r=>r.clan===selected?.clan)).slice(-36),points=selectedHistory.map(h=>h.rows.find(r=>r.clan===selected.clan)?.reputation).filter(v=>typeof v==='number'),min=points.length?Math.min(...points):0,max=points.length?Math.max(...points):1;
  const chart=points.map((v,i)=>`${points.length<2?0:i/(points.length-1)*100},${92-(v-min)/Math.max(1,max-min)*80}`).join(' ');

  function toggleFavorite(clan){setFavorites(cur=>{const next=cur.includes(clan)?cur.filter(x=>x!==clan):[...cur,clan];try{localStorage.setItem(FAVORITES_KEY,JSON.stringify(next));}catch{}return next;});}
  function selectClan(row){setSelectedClan(row.clan);setMembers([]);setMemberPrevious({});loadMembers(row);}
  function exportHistory(){const blob=new Blob([JSON.stringify(history,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='ninja-zenshin-clan-history.json';a.click();URL.revokeObjectURL(u);}

  return <main className="shell">
    <header className="hero"><div><div className="eyebrow"><span className={`dot ${status}`}/> NINJA ZENSHIN // CLAN TRACKER</div><h1>Clan Ranking</h1><p>Live clan reputation and member reputation for <strong>{season}</strong>.</p></div><div className="controls"><button className="ghost" onClick={exportHistory}>⇩ History</button><button className="refresh" onClick={load}>↻ Refresh</button><button className={`toggle ${autoRefresh?'on':''}`} onClick={()=>setAutoRefresh(v=>!v)}><span className="switch"/> Auto {autoRefresh?'ON':'OFF'}</button></div></header>
    <section className="stats"><Stat label="CURRENT #1" value={leader?.clan||'—'} sub={leader?`${formatNumber(leader.reputation)} reputation`:'Loading'}/><Stat label="TRACKED CLANS" value={rows.length||'—'} sub="Live Clan Ranking"/><Stat label="MEMBERS" value={rows.length?`${formatNumber(totalMembers)} / ${formatNumber(totalSlots)}`:'—'} sub={totalSlots?`${Math.round(totalMembers/totalSlots*100)}% capacity`:'Loading'}/><Stat label="AVG. REPUTATION" value={rows.length?formatNumber(averageRep):'—'} sub="Across clans"/></section>
    <section className="toolbar"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clan or master..."/></div><div className="filters"><button className={showFavorites?'filter active':'filter'} onClick={()=>setShowFavorites(v=>!v)}>★ Favorites {favorites.length?`(${favorites.length})`:''}</button><div className="selectWrap"><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="rank">Rank</option><option value="reputation">Reputation</option><option value="members">Members</option></select></div></div><div className="updated">{updatedAt?`Updated ${formatTime(updatedAt)}`:'Connecting...'} {autoRefresh&&<span>• next {countdown}s</span>}</div></section>
    <section className="tableCard"><div className="tableHead"><span>RANK</span><span>CLAN</span><span>MASTER</span><span>MEMBERS</span><span>REPUTATION</span><span>Δ</span><span>★</span></div><div className="rows">{filtered.map(row=><div key={`${row.clan}-${row.rank}`} className="tableRow" onClick={()=>selectClan(row)} role="button" tabIndex={0}><div className={`rank r${row.rank}`}>{row.rank<=3?['♛','◆','◆'][row.rank-1]:`#${row.rank}`}</div><div className="clan"><strong>{row.clan}</strong><div className="bar"><i style={{width:`${row.memberMax?Math.min(100,row.memberCurrent/row.memberMax*100):0}%`}}/></div></div><div className="master">{row.master||'—'}</div><div className="members">{row.memberCurrent}/{row.memberMax}</div><div className="rep">{formatNumber(row.reputation)}</div><div className={`movement ${previous[row.clan]-row.rank>0?'up':previous[row.clan]-row.rank<0?'down':'same'}`}>{previous[row.clan]?(previous[row.clan]-row.rank>0?`↑ ${previous[row.clan]-row.rank}`:previous[row.clan]-row.rank<0?`↓ ${Math.abs(previous[row.clan]-row.rank)}`:'—'):'—'}</div><button className={favorites.includes(row.clan)?'star active':'star'} onClick={e=>{e.stopPropagation();toggleFavorite(row.clan)}}>{favorites.includes(row.clan)?'★':'☆'}</button></div>)}</div></section>
    <section className="analytics"><div className="panel"><div className="panelTop"><div><div className="panelLabel">CLAN REP GAIN</div><h2>{selected?.clan||'—'}</h2></div><div className="metric">{selected?`#${selected.rank}`:'—'}</div></div><div className="gainGrid"><Metric label="CURRENT REP" value={selected?formatNumber(selected.reputation):'—'}/><Metric label="10-MIN GAIN" value={selected?formatNumber(repGain(selected,history)):'—'}/><Metric label="REP / MIN" value={selected?formatNumber(Math.round(repGain(selected,history)/10)):'—'}/><Metric label="MEMBER COUNT" value={selected?`${selected.memberCurrent}/${selected.memberMax}`:'—'}/></div></div><div className="panel chartPanel"><div className="panelTop"><div><div className="panelLabel">REPUTATION HISTORY</div><h2>{selected?.clan||'Select a clan'}</h2></div><div className="tiny">{points.length} snapshots</div></div>{points.length>1?<svg viewBox="0 0 100 100" className="chart" preserveAspectRatio="none"><polyline points={chart} fill="none" stroke="var(--accent)" strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg>:<div className="chartEmpty">Keep the tracker open to build history.</div>}<div className="chartLegend"><span>LOW {formatNumber(min)}</span><span>HIGH {formatNumber(max)}</span></div></div></section>
    <section className="memberPanel"><div className="panelTop"><div><div className="panelLabel">LIVE MEMBERS</div><h2>{selected?.clan||'Select a clan'}</h2></div><div className="memberStatus">{memberStatus==='live'?`● LIVE · ${formatTime(memberUpdatedAt)}`:memberStatus==='loading'?'Loading…':memberStatus==='error'?'Member fetch error':memberStatus==='unavailable'?'Clan ID unavailable':'Select a clan'}</div></div>{memberStatus==='loading'&&<div className="memberEmpty">Fetching live member names, levels and reputation…</div>}{memberStatus==='error'&&<div className="memberEmpty">Unable to fetch live members.</div>}{memberStatus==='unavailable'&&<div className="memberEmpty">No clan ID was returned by the source.</div>}{members.length>0&&<div className="memberTable"><div className="memberHead"><span>#</span><span>MEMBER</span><span>LEVEL</span><span>REPUTATION</span><span>Δ REP</span></div>{members.map((m,i)=>{const d=typeof memberPrevious[m.name]==='number'?m.reputation-memberPrevious[m.name]:0;return <div className="memberRow" key={`${m.name}-${i}`}><span className="memberRank">{i+1}</span><strong>{m.name}</strong><span>{m.level||'—'}</span><span>{formatNumber(m.reputation)}</span><span className={d>0?'movement up':d<0?'movement down':'movement same'}>{d>0?`+${formatNumber(d)}`:d<0?formatNumber(d):'—'}</span></div>})}</div>}</section>
    <footer><span>Source: ninjazenshin.online/?panel=clan-ranking</span><span>Clan ranking + member reputation refresh every 30s</span></footer>
  </main>;
}
function repGain(selected,history){if(!selected)return 0;const cutoff=Date.now()-600000;const old=[...history].reverse().find(h=>new Date(h.capturedAt).getTime()<=cutoff&&h.rows?.some(r=>r.clan===selected.clan))?.rows?.find(r=>r.clan===selected.clan);return old?selected.reputation-old.reputation:0;}
function Stat({label,value,sub}){return <div className="stat"><div className="label">{label}</div><div className="statValue">{value}</div><div className="sub">{sub}</div></div>}
function Metric({label,value}){return <div className="metricCard"><div className="label">{label}</div><div className="metricValue">{value}</div></div>}
