'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';

const REFRESH_MS = 3000;
const HISTORY_KEY = 'nztracker-history-v1';
const SETTINGS_KEY = 'nztracker-settings-v1';
const FALLBACK_SEASON_END = '2026-09-14T00:00:00+08:00';
const formatNumber = value => new Intl.NumberFormat('en-US').format(Number(value || 0));
const formatTime = value => value ? new Date(value).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit', second:'2-digit' }) : '—';
function downloadText(filename, content, type) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.rel = 'noopener'; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
function csvEscape(value) { return `"${String(value ?? '').replace(/"/g, '""')}"`; }
function clanHistoryCsv(history) { const lines = ['timestamp,season,rank,clan,master,members_current,members_max,reputation']; for (const snapshot of history) for (const row of snapshot.rows || []) lines.push([snapshot.capturedAt,snapshot.season || '',row.rank,row.clan,row.master,row.memberCurrent,row.memberMax,row.reputation].map(csvEscape).join(',')); return lines.join('\n'); }

export default function Home() {
  const [rows,setRows]=useState([]),[season,setSeason]=useState('Season 2'),[status,setStatus]=useState('loading'),[updatedAt,setUpdatedAt]=useState(null),[serverTime,setServerTime]=useState(null),[seasonEndsAt,setSeasonEndsAt]=useState(FALLBACK_SEASON_END);
  const [query,setQuery]=useState('');
  const [history,setHistory]=useState([]),[previousRep,setPreviousRep]=useState({}),[totalGain,setTotalGain]=useState({});
  const [selectedClan,setSelectedClan]=useState(null),[members,setMembers]=useState([]),[memberTotalGain,setMemberTotalGain]=useState({}),[memberStatus,setMemberStatus]=useState('idle'),[memberUpdatedAt,setMemberUpdatedAt]=useState(null);
  const [settingsOpen,setSettingsOpen]=useState(false),[settings,setSettings]=useState({autoRefresh:true,compact:false,showCountdown:true});

  useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]'));setSettings(s=>({...s,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}));}catch{}},[]);
  useEffect(()=>{try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{}},[settings]);
  useEffect(()=>{if(!serverTime)return;const timer=setInterval(()=>setServerTime(current=>current?new Date(current.getTime()+1000):current),1000);return()=>clearInterval(timer);},[serverTime]);
  const saveHistory=useCallback(snapshot=>setHistory(current=>{const next=[...current,snapshot].slice(-240);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(next));}catch{}return next;}),[]);
  const load=useCallback(async()=>{try{setStatus('loading');const res=await fetch('/api/clan-ranking?t='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error();const data=await res.json();const now=new Date().toISOString();const serverDate=res.headers.get('date');if(serverDate)setServerTime(new Date(serverDate));if(data.seasonEndsAt)setSeasonEndsAt(data.seasonEndsAt);setRows(current=>{const repSnap={};const nextTotals={...totalGain};current.forEach(r=>{repSnap[r.clan]=r.reputation;});if(data.rows?.length){data.rows.forEach(r=>{const id=String(r.clanId||r.clan);const currentRep=Number(r.reputation||0);const oldRep=typeof repSnap[id]==='number'?repSnap[id]:typeof repSnap[r.clan]==='number'?repSnap[r.clan]:undefined;const gain=oldRep===undefined?0:Math.max(0,currentRep-oldRep);nextTotals[id]=(nextTotals[id]||0)+gain;r.liveGain=gain;r.totalGain=nextTotals[id];});setTotalGain(nextTotals);setPreviousRep(repSnap);saveHistory({capturedAt:now,season:data.season,rows:data.rows});}return data.rows||[];});setSeason(data.season||'Season 2');setUpdatedAt(new Date(now));setStatus('live');}catch{setStatus('error');}},[saveHistory,totalGain]);
  const loadMembers=useCallback(async clan=>{if(!clan?.clanId){setMembers([]);setMemberStatus('unavailable');return;}try{setMemberStatus('loading');const res=await fetch(`/api/clan-members?clanId=${encodeURIComponent(clan.clanId)}&t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error();const data=await res.json();const memberServerDate=res.headers.get('date');if(memberServerDate)setServerTime(new Date(memberServerDate));setMembers(current=>{const nextTotals={...memberTotalGain};(data.members||[]).forEach(member=>{const key=`${clan.clanId}:${member.name.trim().normalize('NFC')}:${member.level}`;const oldRep=current.find(m=>m.name===member.name)?.reputation;const gain=typeof oldRep==='number'?Math.max(0,Number(member.reputation||0)-oldRep):0;nextTotals[key]=(nextTotals[key]||0)+gain;member.gain=gain;member.totalGain=nextTotals[key];});setMemberTotalGain(nextTotals);return data.members||[];});setMemberUpdatedAt(new Date(data.fetchedAt||Date.now()));setMemberStatus('live');}catch{setMemberStatus('error');}},[memberTotalGain]);
  useEffect(()=>{load();if(!settings.autoRefresh)return;const t=setInterval(load,REFRESH_MS);return()=>clearInterval(t);},[load,settings.autoRefresh]);
  useEffect(()=>{if(!selectedClan)return;const onKeyDown=e=>e.key==='Escape'&&setSelectedClan(null);document.addEventListener('keydown',onKeyDown);return()=>document.removeEventListener('keydown',onKeyDown);},[selectedClan]);
  useEffect(()=>{if(!selectedClan||!settings.autoRefresh)return;const t=setInterval(()=>{const clan=rows.find(r=>r.clan===selectedClan.clan);if(clan)loadMembers(clan);},REFRESH_MS);return()=>clearInterval(t);},[selectedClan,rows,loadMembers,settings.autoRefresh]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();const data=q?rows.filter(r=>`${r.clan} ${r.master}`.toLowerCase().includes(q)):[...rows];return data.sort((a,b)=>a.rank-b.rank);},[rows,query]);
  const leader=rows[0],totalMembers=rows.reduce((a,r)=>a+r.memberCurrent,0),totalSlots=rows.reduce((a,r)=>a+r.memberMax,0),averageRep=rows.length?Math.round(rows.reduce((a,r)=>a+r.reputation,0)/rows.length):0;
  const countdown=useMemo(()=>{const diff=Math.max(0,new Date(seasonEndsAt).getTime()-(serverTime?serverTime.getTime():Date.now()));const total=Math.floor(diff/1000);return {days:Math.floor(total/86400),hours:Math.floor(total%86400/3600),minutes:Math.floor(total%3600/60),seconds:total%60};},[seasonEndsAt,serverTime]);
  function selectClan(row){setSelectedClan(row);setMembers([]);setMemberTotalGain({});loadMembers(row);}
  function updateSetting(key,value){setSettings(current=>({...current,[key]:value}));}
  function exportHistoryJson(){downloadText('ninja-zenshin-clan-history.json',JSON.stringify(history,null,2),'application/json;charset=utf-8');}
  function exportHistoryCsv(){downloadText('ninja-zenshin-clan-history.csv',clanHistoryCsv(history),'text/csv;charset=utf-8');}
  const topThree=rows.slice(0,3);

  return <main className={`shell ${settings.compact?'compactMode':''}`}>
    <aside className="sideNav"><div className="brandMark">N<span>Z</span></div><nav><button className="navItem active" aria-label="Leaderboard">▦</button><button className="navItem" aria-label="Clan activity">✦</button><button className="navItem" aria-label="Notifications">♧</button><button className="navItem" aria-label="Members">◈</button></nav><button className={`navItem settings ${settingsOpen?'selected':''}`} aria-label="Settings" aria-expanded={settingsOpen} onClick={()=>setSettingsOpen(v=>!v)}>⚙</button></aside>
    {settingsOpen&&<aside className="settingsPanel" aria-label="Tracker settings"><div className="settingsHeader"><div><span className="panelLabel">TRACKER CONFIG</span><h2>Settings</h2></div><button className="settingsClose" onClick={()=>setSettingsOpen(false)} aria-label="Close settings">×</button></div><div className="settingsBody"><label className="settingRow"><span><strong>Auto refresh</strong><small>Sync rankings and open-clan members every 3 seconds.</small></span><input type="checkbox" checked={settings.autoRefresh} onChange={e=>updateSetting('autoRefresh',e.target.checked)}/></label><label className="settingRow"><span><strong>Compact rows</strong><small>Reduce table row height for more clans on screen.</small></span><input type="checkbox" checked={settings.compact} onChange={e=>updateSetting('compact',e.target.checked)}/></label><label className="settingRow"><span><strong>Show countdown</strong><small>Keep the season countdown visible in the overview.</small></span><input type="checkbox" checked={settings.showCountdown} onChange={e=>updateSetting('showCountdown',e.target.checked)}/></label><button className="settingsRefresh" onClick={()=>{load();if(selectedClan){const clan=rows.find(r=>r.clan===selectedClan.clan);if(clan)loadMembers(clan);}}}>↻ Refresh now</button></div><div className="settingsFooter">Settings are saved automatically on this device.</div></aside>}
    <header className="hero"><div><div className="eyebrow"><span className={`dot ${status}`}/> NINJA ZENSHIN // CLAN TRACKER</div><h1>Leaderboard</h1><p>Live clan reputation and member reputation for <strong>{season}</strong>.</p></div><div className="controls"><span className="liveBadge">● {settings.autoRefresh?'LIVE · SYNCING':'LIVE · PAUSED'}</span><button className="ghost" onClick={exportHistoryJson}>⇩ JSON</button><button className="ghost" onClick={exportHistoryCsv}>⇩ CSV</button></div></header>
    <section className="overview"><div className="overviewStat"><strong>{rows.length||'—'}</strong><span>TRACKED CLANS</span><small>Live clan ranking</small></div><div className="overviewStat"><strong>{rows.length?`${formatNumber(totalMembers)}`:'—'}</strong><span>ACTIVE MEMBERS</span><small>{totalSlots?`${Math.round(totalMembers/totalSlots*100)}% capacity`:'Loading'}</small></div>{settings.showCountdown&&<section className="countdownPanel"><div><div className="countdownEyebrow">REMAINING TIME FOR COMPLETION</div><div className="countdownTitle">{season} <span>ENDS IN</span></div></div><div className="countdownGrid"><CountdownBox value={countdown.days} label="DAYS"/><CountdownBox value={String(countdown.hours).padStart(2,'0')} label="HRS"/><CountdownBox value={String(countdown.minutes).padStart(2,'0')} label="MINS"/><CountdownBox value={String(countdown.seconds).padStart(2,'0')} label="SECS"/></div></section>}</section>
    <section className="podium">{topThree.map((row,index)=><div key={`${row.clan}-podium`} className={`podiumCard p${index+1} ${index===0?'winner':''}`} onClick={()=>selectClan(row)}><div className="podiumTop"><span className="podiumRank">{index+1}</span><div className="avatar">{row.clan?.slice(0,1)||'N'}</div><div className="podiumName"><strong>{row.clan}</strong><small>{row.master||'Clan Master'}</small></div></div><div className="podiumStats"><div><span>MEMBERS</span><strong>{row.memberCurrent}/{row.memberMax}</strong></div><div><span>REPUTATION</span><strong>{formatNumber(row.reputation)}</strong></div><div><span>GAIN</span><strong>+{formatNumber(row.liveGain||0)}</strong></div></div><div className="podiumFooter"><span>#{row.rank} RANK</span><span>● LIVE</span></div></div>)}</section>
    <section className="toolbar"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clan or master..."/></div><div className="toolbarMeta"><div className="updated">{updatedAt?`Updated ${formatTime(updatedAt)}`:'Connecting...'} <span>• {settings.autoRefresh?'LIVE':'PAUSED'}</span></div><div className="serverClock">SERVER TIME <strong>{serverTime?formatTime(serverTime):'—'}</strong></div></div></section>
    <section className="tableCard"><div className="rankingTitle"><h2>Global Ranking</h2><span>{filtered.length} CLANS</span></div><div className="tableHead"><span>RANK</span><span>CLAN</span><span>MASTER</span><span>MEMBERS</span><span>REPUTATION</span><span>GAIN</span><span>TOTAL GAIN</span></div><div className="rows">{filtered.map(row=>{const gain=Number(row.liveGain||0);const total=Number(row.totalGain||0);return <div key={`${row.clan}-${row.rank}`} className={`tableRow ${gain>0?'repGainRow':''}`} onClick={()=>selectClan(row)} role="button" tabIndex={0} onKeyDown={e=>e.key==='Enter'&&selectClan(row)}><div className={`rank r${row.rank}`}>{row.rank}</div><div className="clan"><strong>{row.clan}</strong><div className="bar"><i style={{width:`${row.memberMax?Math.min(100,row.memberCurrent/row.memberMax*100):0}%`}}/></div></div><div className="master">{row.master||'—'}</div><div className="members">{row.memberCurrent}/{row.memberMax}</div><div className={`rep ${gain>0?'repGain':''}`}>{formatNumber(row.reputation)}{gain>0&&<span className="repPop">+{formatNumber(gain)} REP</span>}</div><div className="gainValue">{gain>0?`+${formatNumber(gain)}`:'0'}</div><div className="totalGainValue">{total>0?formatNumber(total):'0'}</div></div>})}{!filtered.length&&<div className="empty">No clans match your search.</div>}</div></section>
    {selectedClan&&<div className="memberModal" role="dialog" aria-modal="true" aria-label={`${selectedClan.clan} live members and reputation history`} onMouseDown={e=>e.target===e.currentTarget&&setSelectedClan(null)}><div className="memberModalBox"><div className="memberModalHeader"><div><div className="panelLabel">LIVE MEMBERS // REPUTATION HISTORY · CLAN #{selectedClan.rank}</div><h2>{selectedClan.clan}</h2><div className="memberModalMeta">Master: {selectedClan.master||'—'} · {selectedClan.memberCurrent}/{selectedClan.memberMax} members</div></div><div className="memberModalActions"><span className="memberStatus">{memberStatus==='live'?`● LIVE · ${formatTime(memberUpdatedAt)}`:memberStatus==='loading'?'Loading…':memberStatus==='error'?'Fetch error':'Unavailable'}</span><button className="modalClose" onClick={()=>setSelectedClan(null)} aria-label="Close members">×</button></div></div><div className="memberModalBody"><div className="liveMembersSummary"><span>LIVE MEMBERS</span><strong>{members.length||selectedClan.memberCurrent||0}</strong><small>{memberStatus==='live'?'Names and reputation synchronized from source':'Waiting for member data…'}</small></div>{memberStatus==='loading'&&<div className="memberEmpty">Fetching live member names, levels and reputation…</div>}{memberStatus==='error'&&<div className="memberEmpty">Unable to fetch live members right now.</div>}{memberStatus==='unavailable'&&<div className="memberEmpty">No clan ID was returned by the source.</div>}{memberStatus==='live'&&!members.length&&<div className="memberEmpty">This clan currently has no members returned by the source.</div>}{members.length>0&&<div className="memberTable"><div className="memberHead"><span>#</span><span>MEMBER</span><span>LEVEL</span><span>REPUTATION</span><span>GAIN</span><span>TOTAL GAIN</span></div>{members.map((member,index)=>{const gain=Number(member.gain||0);const total=Number(member.totalGain||0);return <div className="memberRow" key={`${member.name}-${index}`}><span className="memberRank">{index+1}</span><strong>{member.name}</strong><span>{member.level||'—'}</span><span className={gain>0?'memberRepGain':''}>{formatNumber(member.reputation)}{gain>0&&<span className="repPop">+{formatNumber(gain)} REP</span>}</span><span className={gain>0?'movement up':'movement same'}>{gain>0?`+${formatNumber(gain)}`:'0'}</span><span className="totalGainValue">{total>0?formatNumber(total):'0'}</span></div>})}</div>}</div><div className="memberModalFooter">Live member reputation stays synchronized while this clan is open · Press Esc to close</div></div></div>}
    <footer><span className="footerCredits">Created by <strong>Michol</strong> · <a href="https://discordapp.com/users/396080330702061588" target="_blank" rel="noreferrer">Discord</a></span></footer>
  </main>
}
function CountdownBox({value,label}){return <div className="countdownBox"><strong>{value}</strong><span>{label}</span></div>}
