create table if not exists public.clan_rankings (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  rank integer,
  clan_name text not null,
  master text,
  members integer,
  reputation bigint,
  gain bigint,
  total_gain bigint,
  fetched_at timestamptz not null default now(),
  season integer not null default 0,
  raw_data jsonb
);

create unique index if not exists clan_rankings_clan_season_uidx
  on public.clan_rankings (clan_id, season);

create index if not exists clan_rankings_fetched_at_idx
  on public.clan_rankings (fetched_at desc);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  status text not null,
  clans_count integer not null default 0,
  members_count integer not null default 0,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.clan_rankings enable row level security;
alter table public.sync_runs enable row level security;

create policy "public can read clan rankings"
  on public.clan_rankings for select
  to anon, authenticated
  using (true);

create policy "public can read sync runs"
  on public.sync_runs for select
  to anon, authenticated
  using (true); 
