create table if not exists public.rep_tracker_config (
  id text primary key default 'main',
  clan_id text,
  clan_name text not null default 'Chaos',
  current_season text,
  current_round text,
  final_day_at timestamptz,
  expected_member_count integer,
  sync_interval_seconds integer not null default 45 check (sync_interval_seconds between 30 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rep_tracker_seasons (
  season text primary key,
  clan_id text not null,
  started_at timestamptz not null default now(),
  baseline_created_at timestamptz,
  final_locked_at timestamptz,
  status text not null default 'active' check (status in ('active','locked','archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.rep_tracker_members (
  clan_id text not null,
  member_id text not null,
  current_ign text not null,
  current_level integer not null default 0,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (clan_id, member_id)
);

create table if not exists public.rep_tracker_member_events (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  season text not null,
  member_id text not null,
  event_type text not null check (event_type in ('joined','left','renamed','updated')),
  previous_data jsonb,
  current_data jsonb,
  occurred_at timestamptz not null default now()
);

create table if not exists public.rep_tracker_snapshots (
  id bigint generated by default as identity primary key,
  clan_id text not null,
  season text not null,
  member_id text not null,
  ign text not null,
  level integer not null,
  reputation bigint not null,
  stamina integer,
  max_stamina integer,
  source text not null,
  captured_at timestamptz not null default now(),
  suspicious boolean not null default false,
  suspicious_reason text,
  raw_data jsonb not null default '{}'::jsonb,
  unique (clan_id, season, member_id, captured_at)
);

create table if not exists public.rep_tracker_baselines (
  season text not null,
  clan_id text not null,
  member_id text not null,
  ign text not null,
  level integer not null,
  baseline_rep bigint not null,
  captured_at timestamptz not null default now(),
  primary key (season, clan_id, member_id)
);

create table if not exists public.rep_tracker_hours (
  id bigint generated by default as identity primary key,
  season text not null,
  clan_id text not null,
  member_id text not null,
  work_date date not null,
  start_time timestamptz,
  end_time timestamptz,
  break_minutes integer not null default 0 check (break_minutes >= 0),
  total_hours numeric(10,2) not null check (total_hours >= 0),
  source text not null default 'MANUAL' check (source in ('MANUAL','ADMIN','IMPORT')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rep_tracker_finalizations (
  id bigint generated by default as identity primary key,
  season text not null,
  version integer not null,
  clan_id text not null,
  final_timestamp timestamptz not null,
  server_timestamp timestamptz not null,
  member_count integer not null,
  total_rep bigint not null,
  season_gain bigint not null,
  total_hours numeric(12,2) not null,
  avg_rep_per_hour numeric(12,2),
  locked_by text,
  raw_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique (season, version)
);

create table if not exists public.rep_tracker_sync_runs (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('success','partial','failed')),
  source text,
  season text,
  clan_id text,
  members_returned integer not null default 0,
  members_expected integer,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error_message text,
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.rep_tracker_audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  admin text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_rep_snapshots_member_time on public.rep_tracker_snapshots (clan_id, season, member_id, captured_at desc);
create index if not exists idx_rep_snapshots_season_time on public.rep_tracker_snapshots (clan_id, season, captured_at desc);
create index if not exists idx_rep_hours_member_date on public.rep_tracker_hours (clan_id, season, member_id, work_date desc);
create index if not exists idx_rep_sync_completed on public.rep_tracker_sync_runs (completed_at desc);
create index if not exists idx_rep_events_member on public.rep_tracker_member_events (clan_id, season, member_id, occurred_at desc);

alter table public.rep_tracker_config enable row level security;
alter table public.rep_tracker_seasons enable row level security;
alter table public.rep_tracker_members enable row level security;
alter table public.rep_tracker_member_events enable row level security;
alter table public.rep_tracker_snapshots enable row level security;
alter table public.rep_tracker_baselines enable row level security;
alter table public.rep_tracker_hours enable row level security;
alter table public.rep_tracker_finalizations enable row level security;
alter table public.rep_tracker_sync_runs enable row level security;
alter table public.rep_tracker_audit_log enable row level security;

revoke all on public.rep_tracker_config from anon, authenticated;
revoke all on public.rep_tracker_seasons from anon, authenticated;
revoke all on public.rep_tracker_members from anon, authenticated;
revoke all on public.rep_tracker_member_events from anon, authenticated;
revoke all on public.rep_tracker_snapshots from anon, authenticated;
revoke all on public.rep_tracker_baselines from anon, authenticated;
revoke all on public.rep_tracker_hours from anon, authenticated;
revoke all on public.rep_tracker_finalizations from anon, authenticated;
revoke all on public.rep_tracker_sync_runs from anon, authenticated;
revoke all on public.rep_tracker_audit_log from anon, authenticated;

do $$ begin
  insert into public.rep_tracker_config (id) values ('main') on conflict (id) do nothing;
end $$;
